extended swoole tests

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -83,6 +83,62 @@ jobs:
           NO_INTERACTION=1 TEST_PHP_ARGS="--show-diff --show-clean -q" make test
           php -d extension=$(pwd)/modules/pdo_duckdb.so test.php
 
+  swoole:
+    name: "Swoole"
+    runs-on: ${{ matrix.os }}
+    timeout-minutes: 5
+    strategy:
+      fail-fast: false
+      matrix:
+        os:
+          - ubuntu-22.04
+          - ubuntu-22.04-arm
+          - macos-14
+        php-version:
+          - 8.2
+          - 8.3
+          - 8.4
+          - 8.5
+          - 8.6
+        thread-safety:
+          - zts
+          - nts
+        exclude:
+          - os: macos-14
+            php-version: 8.6
+    steps:
+      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
+        with:
+          persist-credentials: false
+      - name: Setup PHP
+        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
+        with:
+          php-version: ${{ matrix.php-version }}
+          coverage: none
+          extensions: swoole
+        env:
+          phpts: ${{ matrix.thread-safety }}
+      - name: Build & Test
+        run: |
+          case "$os" in
+            ubuntu-22.04)     libduckdb=static-libs-linux-amd64.zip; sudo timedatectl set-timezone "Europe/Berlin" ;;
+            ubuntu-22.04-arm) libduckdb=static-libs-linux-arm64.zip; sudo timedatectl set-timezone "Europe/Berlin" ;;
+            macos-14)         libduckdb=static-libs-osx-arm64.zip; sudo systemsetup -settimezone "Europe/Berlin" ;;
+            *) echo "error os"; exit 1 ;;
+          esac
+          php -m | grep swoole
+          curl -fsSL "https://github.com/duckdb/duckdb/releases/download/v1.5.5/libduckdb-src.zip" -o libduckdb-src.zip
+          unzip -o libduckdb-src.zip duckdb.hpp -d ./
+          curl -fsSL "https://github.com/duckdb/duckdb/releases/download/v1.5.5/${libduckdb}" -o ${libduckdb}
+          unzip -o ${libduckdb} -d ./
+          phpize
+          ./configure --with-pdo-duckdb
+          make
+          php -d extension=$(pwd)/modules/pdo_duckdb.so -m | grep duckdb
+          NO_INTERACTION=1 TEST_PHP_ARGS="--show-diff --show-clean -q" make test
+          php -d extension=$(pwd)/modules/pdo_duckdb.so test.php
+          php -d extension=$(pwd)/modules/pdo_duckdb.so test_swoole.php
+
   windows-build:
     name: Windows
     runs-on: ${{ (matrix.php-version == '8.6' && 'windows-2025-vs2026') || 'windows-2022' }}
