cleanup

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -60,10 +60,10 @@ jobs:
         run: |
           sudo timedatectl set-timezone "Europe/Berlin"
           apt-get update && apt-get install -y --no-install-recommends libgcc-13-dev
-          case "${{ matrix.os }}" in
+          case ${matrix.os} in
             ubuntu-24.04)     libduckdb=static-libs-linux-amd64.zip ;;
             ubuntu-24.04-arm) libduckdb=static-libs-linux-arm64.zip ;;
-            *) echo "error ${{ matrix.os }}"; exit 1 ;;
+            *) echo "error os"; exit 1 ;;
           esac
           curl -fsSL "https://github.com/duckdb/duckdb/releases/download/v1.5.4/libduckdb-src.zip" -o libduckdb-src.zip
           unzip -o libduckdb-src.zip duckdb.h duckdb.hpp -d ./
