added ci for arm and macos

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -19,12 +19,16 @@ jobs:
       - name: Validate
         run: composer validate --strict
 
-  linux:
-    name: "Linux Tests"
-    runs-on: ubuntu-latest
+  linux_macos:
+    name: "Linux & MacOS Tests"
+    runs-on: ${{ matrix.os }}
     strategy:
       fail-fast: false
       matrix:
+        os:
+          - ubuntu-24.04
+          - ubuntu-24.04-arm
+          - macos-14
         php-version:
           - 8.2
           - 8.3
@@ -47,10 +51,16 @@ jobs:
           sudo timedatectl set-timezone Europe/Berlin
           sudo apt-get -y update
           sudo apt-get -y --no-install-recommends install unzip wget
-          wget -q https://github.com/duckdb/duckdb/releases/download/v1.5.4/libduckdb-linux-amd64.zip
-          unzip -o libduckdb-linux-amd64.zip -d ./
+
+          case "${{ matrix.os }}" in
+            ubuntu-24.04)     libduckdb=libduckdb-linux-amd64.zip ;;
+            ubuntu-24.04-arm) libduckdb=libduckdb-linux-arm64.zip ;;
+            macos-14)         libduckdb=libduckdb-osx-universal.zip ;;
+            *) echo "error ${{ matrix.os }}"; exit 1 ;;
+          esac
+          wget "https://github.com/duckdb/duckdb/releases/download/v1.5.4/${libduckdb}"
+          unzip -o libduckdb-*.zip -d ./
           phpize
           ./configure --with-pdo-duckdb
           make -j$(nproc)
-          php -v
           NO_INTERACTION=1 TEST_PHP_ARGS="--show-diff --show-clean -q" make test
